changelog:
  categories:
    - title: ✨ Enhancements
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 🔨 Dependencies
      labels:
        - dependencies
