# https://github.com/ahmadnassri/action-dependabot-auto-merge

name: Dependabot-Build-AutoMerge

on:
  push:
    branches: [ develop ]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [20.x]

    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally. Source: https://hugo.alliau.me/2021/05/04/migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets/#share-your-secrets-with-dependabot
    if: |
       (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: NpmRcGen
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc
        echo "@etipio:registry=https://npm.pkg.github.com/" >> .npmrc

    - name: Install Yarn
      run: npm i yarn -g

    - name: Build
      run: yarn install && yarn build-staging
